pythonname: Daily Shopify Review Scraper

on:
  schedule:
    - cron: '30 3 * * *'  # Runs every day at 9:00 AM IST (3:30 AM UTC)
  workflow_dispatch:       # Allows manual run

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
    - name: Clone the repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run the script
      run: |
        python shopify_reviews_2.py
